kind: pipeline
name: default

steps:
  - name: push commit
    image: appleboy/drone-git-push
    settings:
      branch: master
      remote: git@github.com:gunay5858/SnippezApi.git
      force: false
      commit: true
      ssh_key:
        secret: ssh_private_key
